#!/bin/sh

[ "${ACTION}" = "released" ] || exit 0

. /lib/functions.sh

logger "$BUTTON pressed for $SEEN seconds"

if [ "$SEEN" -le 10 ] && [ "$SEEN" -gt 5 ]
then
	echo "REBOOT" > /dev/console
	sync
	reboot
elif [ "$SEEN" -gt 10 ]
then
	echo "FACTORY RESET" > /dev/console
	jffs2reset -y && reboot &
fi
